### ISSUE TITLE
关于禁赛

### ISSUE THREAD

**Issue by a114514wc** [TinyHai/AutoOralCalculation#1]
可以试着让这个模块绕过封禁条件吗🤔

**Comment by TinyHai** [comment]
> 可以试着让这个模块绕过封禁条件吗🤔

封禁在服务端验证的，禁赛后接口不返回数据的，没法绕

**Comment by a114514wc** [comment]
> > 可以尝试让这个模块绕过封禁条件吗🤔
> 
> 封禁在服务端验证的，禁赛后接口不返回数据的，无法¶

我看B站的一些封禁条件解释视频，好像是答题速度1秒内做5题就会被禁赛

**Comment by TinyHai** [comment]
> > > 可以尝试让这个模块绕过封禁条件吗🤔
> > 
> > 
> > 封禁在服务端验证的，禁赛后接口不返回数据的，无法¶
> 
> 我看B站的一些封禁条件解释视频，好像是答题速度1秒内做5题就会被禁赛

如果只是为了防封，开启`极速模式稳赢`选项就行了，或者手动设置一下`答题模拟间隔`也行

**Comment by a114514wc** [comment]
> > > > 可以尝试让这个模块绕过封锁条件吗🤔
> > > 
> > > 
> > > 封禁在服务端验证的，禁赛后接口不返回数据的，无法¶
> > 
> > 
> > 我看B站的一些封禁条件解释视频，希望是答题速度1秒内做5题就会被禁赛
> 
> 如果只是为了防封，开启`极速模式稳赢`选项就行了，或者手动设置一下`答题模拟间隔`也行

好的，谢谢
