### ISSUE TITLE
分爆了没法改了

### ISSUE THREAD

**Issue by lovelymeng** [TinyHai/AutoOralCalculation#16]
![Screenshot_2024-11-15-20-39-59-151_com fenbi android leo](https://github.com/user-attachments/assets/7427f192-f3e0-43f8-a0c9-3a6422a24572)

**Comment by lovelymeng** [comment]
![Screenshot_2024-11-15-20-42-44-644_com fenbi android leo](https://github.com/user-attachments/assets/1eeaa5fe-3719-4680-ad96-f6be6c9be308)

**Comment by TinyHai** [comment]
不是哥们，我限制 8 位数就是怕溢出，你怎么做到的

**Comment by TinyHai** [comment]
> ![Screenshot_2024-11-15-20-42-44-644_com fenbi android leo](https://github.com/user-attachments/assets/1eeaa5fe-3719-4680-ad96-f6be6c9be308)
> 

你先改成 0，然后再改其他的分数应该就行了

**Comment by lovelymeng** [comment]
反编译把里面的8位改成了0x10 16位数我就试试能不能爆

**Comment by lovelymeng** [comment]
关键是确认进按不了

**Comment by TinyHai** [comment]
> 反编译把里面的8位改成了0x10 16位数我就试试能不能爆

你无敌了xd, 源码就摆在这，你自己想办法吧。

**Comment by ilmilm** [comment]
6啊，兄弟。等下周吧
