### ISSUE TITLE
大佬牛逼

### ISSUE THREAD

**Issue by ilmilm** [TinyHai/AutoOralCalculation#2]
话说练习模式的题目数量能不能改，上周还能改898题以下，这周开了脚本就提交不了了

**Comment by TinyHai** [comment]
不知道，我没考虑过改题目数量，提交不了可能是服务端加了验证

**Comment by ilmilm** [comment]
上上周能一下子1w题，上周发现不能了就改低数量，极限898道题，本周直接G然后找到了你这里。不过有自动跟快速模式，速度也不慢了。

**Comment by TinyHai** [comment]
> 上上周能一下子1w题，上周发现不能了就改低数量，极限898道题，本周直接G然后找到了你这里。不过有自动跟快速模式，速度也不慢了。

目前感觉还是有点慢，已经在搞纯接口调用的了，目前测试大概5000分/秒的样子，主要是之前的方式太吃手机性能了，我手机跑一会直接可以煎鸡蛋了
