### ISSUE TITLE
发现了一个新bug

### ISSUE THREAD

**Issue by 121WW64** [TinyHai/AutoOralCalculation#20]
这个不知道怎么触发，在改分数那里乱按的，我是，然后呢，到了-3000多，我刷回到正数的时候，他给我刷新了榜，去了其他的榜，作者要不弄个专门去到负数的

**Comment by 121WW64** [comment]
> 这个不知道怎么触发，在改分数那里乱按的，我是，然后呢，到了-3000多，我刷回到正数的时候，他给我刷新了榜，去了其他的榜，作者要不弄个专门去到负数的

事情大概就是这样![Screenshot_2024-11-21-23-32-42-002_com.fenbi.android.leo.jpg](https://github.com/user-attachments/assets/d4b83047-6735-4fd3-98a5-8f55dd92067f)

这里只有九个人

**Comment by doomsder** [comment]
我操你妈逼，死全家的废物

**Comment by a114514wc** [comment]
> 我操你妈逼，死全家的废物

怎么又有小学生来这叫了😅

**Comment by 121WW64** [comment]
> 我操你妈逼，死全家的废物

可怜的孩子，妈没了吗
不对，你不配可怜

**Comment by 121WW64** [comment]
> > 这个不知道怎么触发，在改分数那里乱按的，我是，然后呢，到了-3000多，我刷回到正数的时候，他给我刷新了榜，去了其他的榜，作者要不弄个专门去到负数的
> 
> 事情大概就是这样![Screenshot_2024-11-21-23-32-42-002_com.fenbi.android.leo.jpg](https://github.com/user-attachments/assets/d4b83047-6735-4fd3-98a5-8f55dd92067f)
> 
> 这里只有九个人

得了，这是封神榜原来

**Comment by 121WW64** [comment]
> > > 这个不知道怎么触发，在改分数那里乱按的，我是，然后呢，到了-3000多，我刷回到正数的时候，他给我刷新了榜，去了其他的榜，作者要不弄个专门去到负数的
> > 
> > 事情大概就是这样![Screenshot_2024-11-21-23-32-42-002_com.fenbi.android.leo.jpg](https://github.com/user-attachments/assets/d4b83047-6735-4fd3-98a5-8f55dd92067f)
> > 
> > 这里只有九个人
> 
> 得了，这是封神榜原来

原来封神榜的作用是上不了战队榜
