### ISSUE TITLE
今天极速答题和循环答题好像被制裁了，进答题提示加载失败

### ISSUE THREAD

**Issue by sr420r** [TinyHai/AutoOralCalculation#4]
今天极速答题和循环答题好像被制裁了，进答题提示加载失败
![Screenshot_2024-11-09-23-46-58-665_com fenbi android leo](https://github.com/user-attachments/assets/a29089aa-1ca3-4bda-b853-57fd91ebb1fb)

**Comment by sr420r** [comment]
还有自动答题

**Comment by TinyHai** [comment]
目前已经把自动答题给整好了，不过自动上分怕是没法修了，服务端好像对接口进行了限制，调太快直接报错了
