### ISSUE TITLE
建议修改默认配置。

### ISSUE THREAD

**Issue by 216592819** [TinyHai/AutoOralCalculation#5]
现有默认配置几乎全部会被检测。
pk极速模式默认失效。
pk标准模式失效。
可能检测pk频率/间隔/ 耗时？

测试结果，手动测试后。
pk，时间与对方相差30%左右，循环间隔12秒
且pk频率每分钟不大于3次，不会加载错误。
练习模式最低延迟700ms。低于620循环几十次会报错。700ms仅测试100次100题。

**Comment by TinyHai** [comment]
目前没有这个打算
