### ISSUE TITLE
口算练习

### ISSUE THREAD

**Issue by 121WW64** [TinyHai/AutoOralCalculation#8]
现在是不是官方限制了呀，刷着刷着就刷不了了，还有作者你那个你，能不能新增一个功能，就是呢啊，开启之后刷口算练习，发送的时候直接当200题发送出去，就那个抓包的东西，对了，还有那个调试模式是什么东西

**Comment by 121WW64** [comment]
我发现那个不登录的时候，他那个口算练习刷题会更快，大佬，你看能不能做到那个欺骗服务器还没登入，但是又能把分数记到账号身上

**Comment by TinyHai** [comment]
> 我发现那个不登录的时候，他那个口算练习刷题会更快，大佬，你看能不能做到那个欺骗服务器还没登入，但是又能把分数记到账号身上，而且那个他还没有什么限制

你这想法好像挺独特的，有时间研究一下

**Comment by TinyHai** [comment]
> 现在是不是官方限制了呀，刷着刷着就刷不了了，还有作者你那个你，能不能新增一个功能，就是呢啊，开启之后刷口算练习，发送的时候直接当200题发送出去，就那个抓包的东西，对了，还有那个调试模式是什么东西

并不是所有练习都能提交200题，只有部分练习可以

**Comment by 121WW64** [comment]
> > 现在是不是官方限制了呀，刷着刷着就刷不了了，还有作者你那个你，能不能新增一个功能，就是呢啊，开启之后刷口算练习，发送的时候直接当200题发送出去，就那个抓包的东西，对了，还有那个调试模式是什么东西
> 
> 并不是所有练习都能提交200题，只有部分练习可以

主要是之前有那个js。差不多这个东西

**Comment by TinyHai** [comment]
> > > 现在是不是官方限制了呀，刷着刷着就刷不了了，还有作者你那个你，能不能新增一个功能，就是呢啊，开启之后刷口算练习，发送的时候直接当200题发送出去，就那个抓包的东西，对了，还有那个调试模式是什么东西
> > 
> > 
> > 并不是所有练习都能提交200题，只有部分练习可以
> 
> 主要是之前有那个js。差不多这个东西

现在练习接口限制挺多的，不过刷分已经可以不用答题了，虽然不知道能用多久

**Comment by TinyHai** [comment]
稍微研究后，确诊为行不通

**Comment by 121WW64** [comment]
> 稍微研究后，确诊为行不通

现在游客那边好像也限制了一点，现在是一点一点增加，之前贼快的

**Comment by 121WW64** [comment]
> 稍微研究后，确诊为行不通

不~~~（手动狗头）
